export * from './ProfessorsList'
export * from './ProfessorsCreateProfessorButton'
export * from './ProfessorsCreateProfessorModal'
export * from './ProfessorsUpdateProfessorModal'
export * from './ProfessorsUpdateProfessorForm'
export * from './ProfessorsConfirmDeleteModal'